name: Release Update

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create GitHub Release Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Release Notes
        uses: softprops/action-gh-release@v2
        with:
          name: CromaX IDE ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
